"""
inference/stubs/smoke.py
------------------------
Minimal compilable detector templates for smoke-testing the benchmark harness.
"""

STUB_KT = """\
package com.android.tools.lint.checks

import com.android.tools.lint.detector.api.*
import org.jetbrains.uast.UCallExpression
import com.intellij.psi.PsiMethod

class {detector} : Detector(), SourceCodeScanner {{
    companion object {{
        val ISSUE = Issue.create(
            id = "{issue_id}",
            briefDescription = "Stub",
            explanation = "Stub detector generated by smoke test.",
            category = Category.CORRECTNESS,
            priority = 5,
            severity = Severity.WARNING,
            implementation = Implementation({detector}::class.java, Scope.JAVA_FILE_SCOPE)
        ){extra_constants}
    }}

    override fun getApplicableMethodNames(): List<String> = emptyList()
}}
"""

# Extra companion object constants injected only for ApiDetector, which has
# tests that static-import these fields by name.
APIDETECTOR_EXTRA_KT = """

        // Constants expected by ApiDetectorTest static imports.
        @JvmField val UNSUPPORTED: Issue = Issue.create("NewApi", "Stub", "Stub",
            Category.CORRECTNESS, 6, Severity.ERROR,
            Implementation(ApiDetector::class.java, Scope.JAVA_FILE_SCOPE))
        @JvmField val INLINED: Issue = Issue.create("InlinedApi", "Stub", "Stub",
            Category.CORRECTNESS, 6, Severity.WARNING,
            Implementation(ApiDetector::class.java, Scope.JAVA_FILE_SCOPE))
        @JvmField val UNUSED: Issue = Issue.create("UnusedAttribute", "Stub", "Stub",
            Category.CORRECTNESS, 6, Severity.WARNING,
            Implementation(ApiDetector::class.java, Scope.JAVA_FILE_SCOPE))
        @JvmField val OBSOLETE_SDK: Issue = Issue.create("ObsoleteSdkInt", "Stub", "Stub",
            Category.PERFORMANCE, 6, Severity.WARNING,
            Implementation(ApiDetector::class.java, Scope.JAVA_FILE_SCOPE))
        const val KEY_REQUIRES_API = "requiresApi"
        const val REPEATED_API_ANNOTATION_REQUIRES_ALL = true"""

STUB_JAVA = """\
package com.android.tools.lint.checks;

import com.android.tools.lint.detector.api.*;
import java.util.Collections;
import java.util.List;

public class {detector} extends Detector implements SourceCodeScanner {{

    public static final Issue ISSUE = Issue.create(
            "{issue_id}", "Stub", "Stub detector generated by smoke test.",
            Category.CORRECTNESS, 5, Severity.WARNING,
            new Implementation({detector}.class, Scope.JAVA_FILE_SCOPE));

    @Override
    public List<String> getApplicableMethodNames() {{
        return Collections.emptyList();
    }}
}}
"""
